#!/usr/bin/env php
<?php

include __DIR__ . '/bootstrap.php';

$application = new \Symfony\Component\Console\Application();
$application->add(new \Pho\Crm\Command\ScheduleRunCommand());
$application->run();
